### PR TITLE
Fixed option renames for rollup

### PR DESCRIPTION
**Pull request by leonrenkema**
I've changed the config so this plugin will work again with the latest rollup as mentioned in #20

### CODE REVIEW

**Comment by raoulduke** [comment]
This also fixes #19

**Comment by AlexH-HankIT** [comment]
Any chance this gets merged soon?

**Comment by ssun3** [comment]
🙏

**Comment by REBELinBLUE** [comment]
@JeffreyWay ?

**Comment by mtaiyabm** [comment]
Is this fix merged? Still having error with latest version.

**Comment by leonrenkema** [comment]
Still nothing from the maintainer..

**Comment by mtaiyabm** [comment]
With the latest update, the parameter **entry** also changed to **input**. Needs update.

For reference: https://github.com/rollup/rollup/issues/1479

**Comment by waplet** [comment]
Also the commonJS dependency must be changed to higher version.
Quite bad, that such a project is no more updated.

**Comment by mbaierl** [comment]
Open since September - is this package still maintained?

**Pull request closed without merging**
